Feat / Fix: BIMData Design System plugin
bimdata/design-system pull request #169
Opened 2022-02-10 10:00 UTC by NicolasRichel

- fix: plugin factory to include directives properly
 - feat: update build config and add vue3 compatible plugin

2022-02-10 15:55 UTC, Amoki approved these changes

2022-02-11 07:13 UTC, Kurtil requested changes

2022-02-11 07:13 UTC, Kurtil commented on plugin.js
> +          cfg.includedComponents.length === 0 ||
The empty Array here is questionable...

2022-02-14 10:32 UTC, Kurtil approved these changes

2022-02-15 08:01 UTC, merged

2022-02-15 08:02 UTC, Bimdata-io commented
:tada: This PR is included in version 1.2.0-rc.28 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.2.0-rc.28)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.2.0-rc.28)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-03-31 07:45 UTC, Bimdata-io commented
:tada: This PR is included in version 1.2.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.2.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: