add BIMDataColorSelector component
bimdata/design-system pull request #181
Opened 2022-03-22 10:25 UTC by LrxGaelle

2022-03-22 10:39 UTC, Amoki requested changes

2022-03-22 10:39 UTC, Amoki commented on src/BIMDataComponents/BIMDataColorSelector/colors.js
> +  const validColors = Object.entries(colors).filter(
valid colors could be computed once instead of every time we need a color

2022-03-30 11:30 UTC, NicolasRichel approved these changes

2022-04-08 06:40 UTC, NicolasRichel approved these changes

2022-04-08 16:51 UTC, Amoki approved these changes

2022-04-11 14:47 UTC, merged