traduction added
bimdata/design-system pull request #202
Opened 2022-04-28 07:05 UTC by pvilalta

hello team,

This PR brings the traduction to the guided-tour

Paul

2022-04-28 07:13 UTC, Kurtil requested changes

2022-04-28 07:13 UTC, Kurtil commented on src/BIMDataComponents/BIMDataGuidedTour/BIMDataGuidedTour.vue
> +                {{ this.translate("continue") }}
this ??

2022-04-28 07:13 UTC, Kurtil commented on src/BIMDataComponents/BIMDataGuidedTour/BIMDataGuidedTour.vue
> +                {{ this.translate("skip") }}
this ??

2022-04-28 07:14 UTC, Kurtil commented
`this` in template should be remove imo

2022-04-28 07:22 UTC, NicolasRichel approved these changes

2022-04-28 07:22 UTC, Kurtil approved these changes

2022-04-28 07:23 UTC, merged

2022-04-28 07:24 UTC, Bimdata-io commented
:tada: This PR is included in version 1.4.0-rc.8 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.4.0-rc.8)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.4.0-rc.8)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-19 13:34 UTC, Bimdata-io commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.0.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: