feat(components): add autoclear prop to search-autocomplete
bimdata/design-system pull request #224
Opened 2022-07-26 14:16 UTC by NicolasRichel

2022-07-26 16:08 UTC, LrxGaelle commented
Would it be possible to have the opposite behavior by default ?

2022-07-27 13:45 UTC, LrxGaelle requested changes
Would it be possible to have the opposite behavior by default ?
This would correspond more to our usual behaviors

2022-07-28 07:03 UTC, NicolasRichel commented
OK, I'll change the props default value.

2022-07-28 07:16 UTC, LrxGaelle approved these changes

2022-07-28 07:19 UTC, merged

2022-07-28 07:21 UTC, Bimdata-io commented
:tada: This PR is included in version 1.4.0-rc.31 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.4.0-rc.31)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.4.0-rc.31)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-19 13:33 UTC, Bimdata-io commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.0.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: