dropdown-menu / style and subListMaxHeight props
bimdata/design-system pull request #228
Opened 2022-08-11 13:20 UTC by pvilalta

2022-08-11 13:24 UTC, Kurtil approved these changes

2022-08-11 13:26 UTC, Amoki requested changes

2022-08-11 13:26 UTC, Amoki commented on src/web/views/Components/DropdownMenu/DropdownMenu.vue
> +          "Use this props to define the sub-list maximum length",
heigth

2022-08-11 13:30 UTC, Amoki approved these changes

2022-08-11 13:31 UTC, merged

2022-08-11 13:32 UTC, Bimdata-io commented
:tada: This PR is included in version 1.4.0-rc.37 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.4.0-rc.37)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.4.0-rc.37)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-19 13:33 UTC, Bimdata-io commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.0.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: