review / add missing doc + check attributes
bimdata/design-system pull request #257
Opened 2022-12-01 09:49 UTC by pvilalta

- [x] I have tested my component
- [x] I have updated the documentation or there is no documentation needed

2022-12-01 09:51 UTC, Kurtil approved these changes

2022-12-01 10:15 UTC, LrxGaelle commented
It's possible to add in `DropdownMenu.vue` file, by default, `checkboxHeaderChecked` and `checkboxElementSlotChecked` data to "true" instead of false (line 150 and 153) to not have a default "empty" component on the page ?

2022-12-01 10:24 UTC, NicolasRichel requested changes

2022-12-01 10:24 UTC, NicolasRichel commented on src/web/views/Components/DropdownList/DropdownList.vue
> +        ["Slot name", "Description"],
There is a typo here, should be `"Event name"` instead of `"Slot name"`.

2022-12-01 10:24 UTC, NicolasRichel commented on src/web/views/Components/Pagination/Pagination.vue
> +        ["Slot name", "Description"],
Same here, should be `"Event name"` instead of `"Slot name"`.

2022-12-01 12:38 UTC, NicolasRichel approved these changes

2022-12-01 12:39 UTC, merged

2022-12-01 12:41 UTC, Bimdata-io commented
:tada: This PR is included in version 1.4.0-rc.72 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.4.0-rc.72)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.4.0-rc.72)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-19 13:31 UTC, Bimdata-io commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.0.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: