Feature/bimdata menu components
bimdata/design-system pull request #262
Opened 2022-12-14 17:01 UTC by LrxGaelle

- [ ] I have tested my component
- [ ] I have updated the documentation or there is no documentation needed

2022-12-15 14:56 UTC, NicolasRichel approved these changes

2022-12-20 09:15 UTC, Kurtil requested changes

2022-12-20 09:15 UTC, Kurtil commented on src/BIMDataComponents/BIMDataMenuInline/BIMDataMenuInline.vue
> +
What is this space for ?

2022-12-20 09:15 UTC, Kurtil commented on src/web/views/Components/Menu/BasicMenu.vue
> +import { basicOptions } from "./option-sets";
Missing file extension.

2022-12-20 09:15 UTC, Kurtil commented on src/web/views/Components/Menu/slots-menu-inline.js
> +  ["submenu", "Use this slot for add a submenu"],
Use this slot *to* add a submenu

2022-12-20 09:15 UTC, Kurtil commented on src/web/views/Components/Menu/Menus.vue
> +import slotsBasicMenu from "./slots-basic-menu";
Missing file extensions.

2022-12-20 09:18 UTC, Kurtil commented on src/BIMDataComponents/BIMDataMenu/BIMDataMenu.vue
> +      return (childPos.height - itemPos.height) * -1;
You can use destructuring here if you want:

```js
const { height: itemPosHeight } = currentItem[0].getBoundingClientRect();
const { height: childPosHeight } = currentChild[0].getBoundingClientRect();

return (childPosHeight - itemPosHeight) * -1;
```

2022-12-20 09:19 UTC, Kurtil commented on src/BIMDataComponents/BIMDataMenu/BIMDataMenu.vue
> +      if (!item.children.position || !item.children.position === "up") return 0;
```js
!item.children.position === "up"
```

may be replace by:

```js
item.children.position !== "up"
```

2022-12-20 09:26 UTC, Kurtil requested changes

2022-12-20 09:26 UTC, Kurtil commented on src/web/views/Components/Menu/props-menu-inline.js
> +    "Set this props to 'false' if you want to open the submenu on the left",
Remove 'if you want'

2022-12-20 09:26 UTC, Kurtil commented on src/web/views/Components/Menu/props-menu-inline.js
> +    "Set this props to false if you don't want the menu component to close when you click outside.",
"If false, the menu component closes when you click outside."

2022-12-20 09:26 UTC, Kurtil commented on src/web/views/Components/Menu/props-basic-menu.js
> +    "Set this props to false if you don't want the menu component to close when you click outside.",
"If false, the menu component closes when you click outside."

2022-12-20 10:01 UTC, Kurtil approved these changes

2022-12-20 22:10 UTC, merged

2022-12-20 22:12 UTC, Bimdata-io commented
:tada: This PR is included in version 1.4.0-rc.77 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/1.4.0-rc.77)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v1.4.0-rc.77)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-19 13:31 UTC, Bimdata-io commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.0.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: