Feature/search in select
bimdata/design-system pull request #315
Opened 2023-10-05 09:37 UTC by LrxGaelle

- [ ] I have tested my component
- [x] I have updated the documentation or there is no documentation needed

## Libraries that use the DS (need to merge first)

- [ ] [BCF Components](https://github.com/bimdata/bcf-components)
- [ ] [BIMData Components](https://github.com/bimdata/bimdata-components)
- [ ] [Building maker](https://github.com/bimdata/building-maker)

## Repos that use the DS (and that I need to check after libraries have been merged)

- [ ] [Viewer](https://github.com/bimdata/viewer)
- [ ] [Platform](https://github.com/bimdata/platform)
- [ ] [SDK](https://github.com/bimdata/bimdata-viewer-sdk)
- [ ] [Marketplace](https://github.com/bimdata/marketplace-front)
- [ ] [Documentation](https://github.com/bimdata/documentation)

2023-10-05 12:46 UTC, Amoki commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectSingle.vue
> +          return option.toLowerCase().includes(this.searchText.toLowerCase());
`this.searchText.toLowerCase()` is called for each option.
Can you compute it once before to improve performance?

2023-10-06 07:12 UTC, NicolasRichel requested changes

2023-10-06 07:12 UTC, NicolasRichel commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectMulti.vue
> +      default: "Search",
I would rather let an empty string as default value for `searchPlaceholder` to avoid i18n issues.

2023-10-06 07:12 UTC, NicolasRichel commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectSingle.vue
> +      default: "Search",
Same remark as previous comment (let default to `""` to avoid i18n issues).

2023-10-06 07:21 UTC, NicolasRichel approved these changes

2023-10-06 08:59 UTC, Kurtil commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectMulti.vue
> +          return option.toLowerCase().includes(lowerCaseSearchText);
May have been an implicit return :P

2023-10-06 09:03 UTC, Kurtil requested changes

2023-10-06 09:03 UTC, Kurtil commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectMulti.vue
> +        return (this.searchText = "");
Is the return really needed ?

2023-10-06 09:03 UTC, Kurtil commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectSingle.vue
> +          return option.toLowerCase().includes(lowerCaseSearchText);
Implicit return ? :)

2023-10-06 09:03 UTC, Kurtil commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectSingle.vue
> +        return (this.searchText = "");
`return` needed ?

2023-10-06 09:31 UTC, Amoki requested changes

2023-10-06 09:31 UTC, Amoki commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectMulti.vue
> +          option.toLowerCase().includes(lowerCaseSearchText),
```suggestion
          option.toLowerCase().includes(lowerCaseSearchText)
```

2023-10-06 09:31 UTC, Amoki commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectMulti.vue
> +          option.toLowerCase().includes(lowerCaseSearchText),
Curiosity question: is this comma a https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Comma_operator in this case?

2023-10-06 09:31 UTC, Amoki commented on src/BIMDataComponents/BIMDataSelect/BIMDataSelectSingle.vue
> +          option.toLowerCase().includes(lowerCaseSearchText),
idem

2023-10-06 14:40 UTC, Kurtil approved these changes

2023-10-10 13:27 UTC, merged

2023-10-10 13:27 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0-rc.1 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0-rc.1)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0-rc.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-27 09:37 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: