[WIP] add search bar into BIMDataDropdownList component
bimdata/design-system pull request #316
Opened 2023-10-06 07:53 UTC by LrxGaelle

- [ ] I have tested my component
- [x] I have updated the documentation or there is no documentation needed

## Libraries that use the DS (need to merge first)

- [ ] [BCF Components](https://github.com/bimdata/bcf-components)
- [ ] [BIMData Components](https://github.com/bimdata/bimdata-components)
- [ ] [Building maker](https://github.com/bimdata/building-maker)

## Repos that use the DS (and that I need to check after libraries have been merged)

- [ ] [Viewer](https://github.com/bimdata/viewer)
- [ ] [Platform](https://github.com/bimdata/platform)
- [ ] [SDK](https://github.com/bimdata/bimdata-viewer-sdk)
- [ ] [Marketplace](https://github.com/bimdata/marketplace-front)
- [ ] [Documentation](https://github.com/bimdata/documentation)

2023-10-06 08:28 UTC, Amoki approved these changes

2023-10-10 13:28 UTC, Kurtil requested changes

2023-10-10 13:28 UTC, Kurtil commented on src/BIMDataComponents/BIMDataDropdownList/BIMDataDropdownList.vue
> +        return this.list.filter(element => {
may be an implicit return :)

2023-10-10 13:31 UTC, Kurtil approved these changes

2023-10-10 13:31 UTC, merged

2023-10-10 13:32 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0-rc.2 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0-rc.2)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0-rc.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-27 09:37 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: