[WIP] create BIMDataInputOutlined component and add documentation
bimdata/design-system pull request #329
Opened 2023-12-07 15:33 UTC by LrxGaelle

- [ ] I have tested my component
- [ ] I have updated the documentation or there is no documentation needed

## Libraries that use the DS (need to merge first)

- [ ] [BCF Components](https://github.com/bimdata/bcf-components)
- [ ] [BIMData Components](https://github.com/bimdata/bimdata-components)
- [ ] [Building maker](https://github.com/bimdata/building-maker)

## Repos that use the DS (and that I need to check after libraries have been merged)

- [ ] [Viewer](https://github.com/bimdata/viewer)
- [ ] [Platform](https://github.com/bimdata/platform)
- [ ] [SDK](https://github.com/bimdata/bimdata-viewer-sdk)
- [ ] [Marketplace](https://github.com/bimdata/marketplace-front)
- [ ] [Documentation](https://github.com/bimdata/documentation)

2023-12-12 10:56 UTC, Kurtil requested changes

2023-12-12 10:56 UTC, Kurtil commented on src/BIMDataComponents/BIMDataInputOutlined/BIMDataInputOutlined.vue
> +      this.$refs.input && this.$refs.input.focus();
optional chaining ? :)

2023-12-12 10:56 UTC, Kurtil commented on src/BIMDataComponents/BIMDataInputOutlined/BIMDataInputOutlined.vue
> +      this.$refs.input && this.$refs.input.blur();
optional chaining ? :)

2023-12-12 10:56 UTC, Kurtil commented on src/web/views/Components/Input/props-data.js
> +    "Use this boolean to check if your input is bad.",
`bad` ? ^^ `incorrect` may be more appropriate isn't it ?

2023-12-12 10:56 UTC, Kurtil commented on src/web/views/Components/Input/props-data.js
> +    "Use this boolean to check if your input is good.",
`correct` ?

2023-12-12 10:56 UTC, Kurtil commented on src/web/views/Components/Input/props-outlined-input.js
> +    "Use this boolean to check if your input is bad.",
idem

2023-12-12 10:56 UTC, Kurtil commented on src/web/views/Components/Input/props-outlined-input.js
> +    "Use this boolean to check if your input is good.",
idem

2023-12-13 08:31 UTC, NicolasRichel approved these changes

2023-12-15 08:19 UTC, merged

2023-12-15 08:19 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0-rc.11 :tada:

The release is available on:
- [npm package (@next dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0-rc.11)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0-rc.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2024-06-27 09:37 UTC, Bimdata-io commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bimdata/design-system/v/2.1.0)
- [GitHub release](https://github.com/bimdata/design-system/releases/tag/v2.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: